import { NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';
import PDFDocument from 'pdfkit';

export async function POST(req: Request) {
  try {
    const config = await req.json();

    // Ensure directory exists
    const reportsDir = path.join(process.cwd(), 'data', 'reports');
    fs.mkdirSync(reportsDir, { recursive: true });

    const filename = `report_${Date.now()}.pdf`;
    const filePath = path.join(reportsDir, filename);

    // Create a dummy PDF using PDFKit
    const doc = new PDFDocument({ margin: 50 });
    const writeStream = fs.createWriteStream(filePath);
    doc.pipe(writeStream);

    doc.fillColor('#333333')
       .fontSize(24)
       .text('AEGIS PRO Inspection Report', { align: 'center' })
       .moveDown();
       
    doc.fontSize(12)
       .text(`Generated on: ${new Date().toISOString()}`)
       .text(`Type: ${config.type}`)
       .text(`Target: ${config.target}`);
       
    doc.moveDown().text('This is an auto-generated PDF report. Charts and full details are embedded in the production pipeline.');

    // Footer
    doc.fontSize(10)
       .fillColor('#888888')
       .text('Generated by AEGIS PRO | CONFIDENTIAL', 50, doc.page.height - 50, { align: 'center', lineBreak: false });

    doc.end();

    // Wait for the file to finish writing
    await new Promise((resolve) => writeStream.on('finish', resolve));

    // Generate mock data for the HTML preview
    const reportData = {
      summary: "AEGIS-Inspector AI Analysis: The structure exhibits overall stability, but critical attention is required on the NW Facade. Two high-priority cracks were identified with 92% confidence. Immediate remediation is recommended to prevent water ingress.",
      stats: { total: 14, critical: 2, flights: config.flights?.length || 1, healthScore: 82 },
      priorityItems: [
        { id: 'p1', zone: 'NW Facade', type: 'crack', gps: '34.0522, -118.2437', flight: 'Flight 001', action: 'Immediate Sealant', urgency: 5, conf: 92, img: 'https://images.unsplash.com/photo-1590492825656-9a54523fa5d9?auto=format&fit=crop&q=80&w=150' },
        { id: 'p2', zone: 'SE Pylon', type: 'spalling', gps: '34.0524, -118.2435', flight: 'Flight 001', action: 'Concrete Patch', urgency: 4, conf: 85, img: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&q=80&w=150' },
      ],
      inventory: [
        { id: 'i1', zone: 'NW Facade', flight: 'Flight 001', type: 'crack', severity: 'CRITICAL', conf: 92, gps: '34.0522, -118.2437', action: 'Immediate Sealant' },
        { id: 'i2', zone: 'SE Pylon', flight: 'Flight 001', type: 'spalling', severity: 'HIGH', conf: 85, gps: '34.0524, -118.2435', action: 'Concrete Patch' },
        { id: 'i3', zone: 'North Pillar', flight: 'Flight 002', type: 'corrosion', severity: 'MEDIUM', conf: 76, gps: '34.0530, -118.2440', action: 'Monitor' },
      ],
      flights: [
        { id: 'Flight 001', date: '2026-05-14', frames: 24, alt: '40m', duration: '12m 30s', bounds: '34.05,-118.24' },
        { id: 'Flight 002', date: '2026-05-13', frames: 18, alt: '45m', duration: '9m 15s', bounds: '34.05,-118.24' },
      ]
    };

    return NextResponse.json({ 
      success: true, 
      reportPath: filePath, 
      downloadUrl: `/api/report/download?file=${filename}`, 
      pageCount: 3, 
      defectCount: 14,
      reportData
    });
  } catch (error) {
    console.error(error);
    return NextResponse.json({ error: 'Failed to generate report' }, { status: 500 });
  }
}
